# Generated by Django 3.1.2 on 2020-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.TextField(blank=True, default=''),
        ),
    ]
